name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  first_task:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build parser
      run: make build
      working-directory: ./1

    - name: Run tests
      run: make test
      working-directory: ./1
